#! /bin/sh
#
#	The Balsa Asynchronous Hardware Synthesis System
#	Copyright (C) 1995-2006 School of Computer Science
#	The University of Manchester, Oxford Road, Manchester, UK, M13 9PL
#	
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
#	
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#	
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

if [ $# -ne 0 ]; then
  if [ "$1" = "--fast" ] || [ "$1" = "-fast" ] || [ "$1" = "fast" ]; then
    shift
	breeze-sim-fast $*
    exit
  elif [ "$1" = "--early" ] || [ "$1" = "-early" ] || [ "$1" = "early" ]; then
    shift
	breeze-sim-early $*
    exit
  elif [ "$1" = "--debug" ] || [ "$1" = "-debug" ] || [ "$1" = "debug" ]; then
    shift
	breeze-sim-debug $*
    exit
  fi
fi

if [ "${BREEZE_SIM_OPTS}" = "--fast" ] || [ "${BREEZE_SIM_OPTS}" = "-fast" ] || [ "${BREEZE_SIM_OPTS}" = "fast" ]; then
	breeze-sim-fast $*
elif [ "${BREEZE_SIM_OPTS}" = "--early" ] || [ "${BREEZE_SIM_OPTS}" = "-early" ] || [ "${BREEZE_SIM_OPTS}" = "early" ]; then
	breeze-sim-early $*
else
	breeze-sim-debug $*
fi
