/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_MainWindow2 (void);
GtkWidget *create_GTKWaveRunningDialogue (void);
GtkWidget *create_ProcessStillRunning (void);
GtkWidget *create_SourceViewWindow (void);
GtkWidget *create_TimeLineBehaviourViewWindow (void);
GtkWidget *create_InfoProcessCrashed (void);
GtkWidget *create_BreezeSimCtrlAlreadyRunning (void);
GtkWidget *create_GraphviewShortcutsHelpWindow (void);
GtkWidget *create_NoTraceFileDialogue (void);
