#! /bin/sh
exec perl -x $0 ${1+"$@"}
    if 0;
#!perl

# Fixup bugs generated by rex in BreezeScan.c and BalsaScan.c
# change:
#   ExtendArray ((char * *) & yyStateStack, & yyStateStackSize, sizeof (yyStateRange));
# into:
#   ExtendArray_FIXED ((char * *) & yyStateStack, & yyStateStackSize, sizeof (yyStateRange));


while (<>)
{
	$line = $_;

	if ($line =~ /ExtendArray/ and $line =~ /yyStateStack/ )
	{
	  $line =~ s/ExtendArray/ExtendArray_FIXED/;
	}

	print $line;
}
